### ISSUE TITLE
Conflict between `once` and `on` if the same function is used

### ISSUE THREAD

**Issue by chocolateboy** [Alex1990/little-emitter#5]
Registering a listener with `once` contaminates the function so that it can only ever be called once.

### Test

```javascript
const Emitter = require('little-emitter')

let count = 0

function log (type) {
    console.log([++count, type])
}

const emitter = new Emitter()

emitter.once('test', log)
emitter.emit('test', 'once')
emitter.emit('test', 'once')

emitter.on('test', log)
emitter.emit('test', 'on')
emitter.emit('test', 'on')
```

### Expected Output

```
[ 1, 'once' ]
[ 2, 'on' ]
[ 3, 'on' ]
```

### Actual Output

```
[ 1, 'once' ]
[ 2, 'on' ]
```
The same issue occurs if a function registered with `on` is subsequently registered with `once`.

The underlying issue here is that "onceness" is [attached to the function](https://github.com/Alex1990/little-emitter/blob/61283c9fc28dc8761410e0d8c9e8249cb864c22a/src/index.js#L27) (which might also conflict with other code/libraries), rather than being a property of the subscription.

### Environment

- **little-emitter**: v0.3.4
- **Node.js**: v14.9.0
- **OS**: Linux (Arch)

**Comment by Alex1990** [comment]
Fixed in release 0.3.5. Very thanks :)
